name: release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "track/**"

permissions:
    contents: write
    pull-requests: write

jobs:
  release:
      name: release
      uses: canonical/identity-team/.github/workflows/charm-release.yaml@6682f5f0364dfd050360059e2d68d21dfe7316cc # v1.7.2
      secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
