# Release charm's libraries if they have changed
name: Release Libraries

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/oathkeeper/**"

jobs:
  release-lib:
    name: Release any bumped library
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@b5428d226e364de1c5ad601c1ec27c333f489d1d # v1.16.2
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
